apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd-priority
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      priorityClassName: httpd-high-priority
      containers:
      - image: httpd
        name: httpd-priority
        resources:
          requests:
            memory: 100Mi
            cpu: 150m
          limits:
            memory: 1200Mi
            cpu: 1500m 
