apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    #nodeSelector: cpu=1
    ignorePvcPods: true
    strategies:
      "LowNodeUtilization":
         enabled: true
         params:
           thresholdPriority: 1000000
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 75
               "memory": 75
               "pods": 75
             targetThresholds:
               "cpu" : 80
               "memory": 80
               "pods": 100
